### PR TITLE
Fixed Mobileview of Home Page

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Fixed Mobileview of Home Page - Solved #1900
Kindly go through this PR @panwar8279

https://github.com/user-attachments/assets/83d3cdb9-9998-4c39-9a2c-7558d5bf24d4

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@panwar8279 Kindly please go through this PR and also add level label to  #1925 this PR since it is already merged

**Comment by sailaja-adapa** [comment]
@panwar8279 Kindly please go through this PR and also add level label to #1925  this PR since it is already merged

**Comment by sailaja-adapa** [comment]
@panwar8279 Kindly please go through this PR and also add level label to #1925  this PR since it is already merged

**Comment by sailaja-adapa** [comment]
@panwar8279 Kindly Please go through this PR

**Comment by sailaja-adapa** [comment]
@panwar8279 kindly please go through this PR

**Comment by sailaja-adapa** [comment]
@panwar8279 Kindly go through this PR

**Comment by panwar8279** [comment]
Please create new pr.

**Pull request closed without merging**
