### PR TITLE
[Feature Request]: Category Based Sorting

### LINKED ISSUE #767: [Feature Request]: Adding Sorting Based on Categories
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The sorting feature based on categories will help users search for and use tools according to their requirements. We can implement tools for developers, designers, movies, AI, resume building, and more such categories

### Use Case

This feature will be beneficial and user-friendly because DevLabs has more than 400 tools and extensions. We need sorting based on categories so that users can find and explore features that are suitable for their requirements.

### Benefits

This would benefit users by allowing them to search for and explore the tools they need. As we continue to add more tools and may soon surpass 1,000, it is essential to categorize them and implement a sort-by-category feature.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Kiran-pande-30**
## Related Issue
Fixes #767 

## Description
 I would love to add the Category Based Sorting Feature to our product.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots/videos (if applicable)

https://github.com/HimanshuNarware/Devlabs/assets/105718863/1a71fd72-5f35-48a6-b384-64ea3bf9aca7

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X} I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Hello @panwar8279, I raised the PR on this issue last week, and had to resolve all the file and code conflicts. I am rasing the PR again hoping for "Merged" this time.

### CODE REVIEW

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279 I request you to please merge this PR

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279, please review this PR, It can have merge conflicts once other PR are merged.

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279 Please review this pull request

**Comment by panwar8279** [comment]
@Kiran-pande-30 , Please solve file conflict issue.

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279 i have resolved the merge conflicts please review this PR, and merge it so that i don't get any more merge conflicts

**Comment by panwar8279** [comment]
@Kiran-pande-30 , Home.js  have file conflict issue, please fix it.

**Pull request closed without merging**
