### PR TITLE
Pagination component

### PR DESCRIPTION
**Pull request by davidkrupa**
The pagination component works and can be reused throughout the website. The pagination functionality itself has a few bugs, but I'll open another issue that reflects this since this issue was only about creating a reusable component.

#105

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@davidkrupa pagination still has some issues. correct them

Screenshot 2023-10-23 122128
Screenshot 2023-10-23 122138
Screenshot 2023-10-23 122106

**Comment by davidkrupa** [comment]
@HimanshuNarware as I wrote, the problems you are talking about are problems that existed before. This topic is only about creating reusable component. I will make a new issue and I can solve it if you want. Please merge this pull request.

**Comment by davidkrupa** [comment]
@HimanshuNarware please merge it otherwise this branch will have more and more conflicts

**Comment by HimanshuNarware** [comment]
> > @HimanshuNarware please merge it otherwise this branch will have more and more conflicts
> 
> ok

but first resolve all conflicts

**Comment by davidkrupa** [comment]
@HimanshuNarware conflicts resolved should be ready for merge

**Pull request merged**
