### PR TITLE
Add Style to Notification

### PR DESCRIPTION
**Pull request by panam1916**
## Related Issue
Include new style to notifiaction Issue #364

## Description
Use react toast for styling notification

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
pr_ss_2
remove

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by panam1916** [comment]
Can there be Dependency reason for deployment error? because in this react-toast dependency use

**Comment by panwar8279** [comment]
Take updated code then add this feature. You have outdated code. Check in both light and dark mode.

**Comment by panam1916** [comment]
> Take updated code then add this feature. You have outdated code. Check in both light and dark mode.

ok and i create new pr or just push in this

**Comment by panam1916** [comment]
Again , I update add feature in updated code as you say , so why this happen ?

**Pull request closed without merging**
