### PR TITLE
 Added New tool

### PR DESCRIPTION
**Pull request by root-0101**
Done #212 
I added a new tool called **PortSwigger** in the "ethical" category

Screenshot (68)

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@root-0101 feel free to create more issues, also starred our repo :)

**Comment by root-0101** [comment]
Hey @HimanshuNarware Please allow me to add more tools in "ethical" category

picoCTF - https://www.picoctf.org/  
picoCTF is a fun and educational online platform where you can learn and practice cybersecurity skills through a series of challenges.

Screenshot (69)

overTheWire - https://overthewire.org/wargames/
OverTheWire is a community of hackers who offer fun-filled games to help you learn and practice security concepts. 

Screenshot (70)

**Comment by root-0101** [comment]
Please assign me the required levels for this PR

**Comment by root-0101** [comment]
Please assign me the required levels for this successfully merged PR

**Comment by root-0101** [comment]
Hey @HimanshuNarware @panwar8279 Please assign me the required levels for this successfully merged PR

**Pull request merged**
