### PR TITLE
Added shadows to the buttons in home and about sections.

### PR DESCRIPTION
**Pull request by Rakshit-gen**
Solved Isssue #219

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Rakshit-gen  share a demo video

**Comment by Rakshit-gen** [comment]
Sure @HimanshuNarware wait

**Comment by Rakshit-gen** [comment]
image
image

Due to storage and battery issues with my laptop, I might not be able to create a video of what effects I added.
But here's a pair of images of shadows I added.
In first image it's of when the cursor hovers over star the repo
and In second image it is of when the mouse hovers over the buttons in cards on the home page.
Thank you! I hope you like the effects.

**Comment by Rakshit-gen** [comment]
Preview is available here - https://vercel.live/open-feedback/devlabs-git-fork-rakshit-gen-main-himanshunarwares-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

**Comment by Rakshit-gen** [comment]
Hey @HimanshuNarware Please check if it is according to your expectations or not and merge the pull request.

**Pull request merged**
