### PR TITLE
Sidebar missing links

### LINKED ISSUE #1174: [Feature Request]:  NavItems Missing in Responsive burger menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

check this out,

### Use Case

Navbar items missing in responsive menu

### Benefits

they don't have rate us and other stuff in responsive devices

### Add ScreenShots

image

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@panwar8279 

[Feature Request]: NavItems Missing in Responsive burger menu #1174

close #1174

## Description
[Please include a brief description of the changes or features added]

- added all missing navigation links to sidebar

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@panwar8279 

kindly please check this and merge it

**Comment by panwar8279** [comment]
@dhruv8433 , Please solve file conflict issue.

**Comment by dhruv8433** [comment]
@panwar8279 

now you can merge this

**Comment by panwar8279** [comment]
hi @dhruv8433 ,There are some deployment error, create new pr for this.

**Pull request closed without merging**
