### PR TITLE
Added tilt Effect

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## Description
I have added the tilt effect on the header image .

closes : #876 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/HimanshuNarware/Devlabs/assets/118350936/4cbc1f46-f366-4ccb-8be7-a1688d6bb9e2

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@HimanshuNarware  Please review this

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  Please review this

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  Mam it has been more than 5 days please review this

**Comment by panwar8279** [comment]
There are some deployments error. Please create pr again.

**Comment by Ayushmaanagarwal1211** [comment]
Ok creating

**Pull request closed without merging**
