### PR TITLE
About section is fixed

### PR DESCRIPTION
**Pull request by NitinChakrawarti**
Now logo and description of logo is visible in single screen without scrolling. 

Screenshot 2024-05-14 154824

issue no is #283

### CODE REVIEW

**Comment by NitinChakrawarti** [comment]
@AshutoshDash1999 as per GSSoC'24 guidelines please add label regarding level of issue and assign this PR to me.

**Comment by NitinChakrawarti** [comment]
@tedante as per GSSoC'24 guidelines please add label regarding level of issue and assign this PR to me.

**Comment by AshutoshDash1999** [comment]
> @AshutoshDash1999 as per GSSoC'24 guidelines please add label regarding level of issue and assign this PR to me.

Bro if you don't know whom to tag, just tag the project owner. I am only a contributor.

**Comment by NitinChakrawarti** [comment]
> > @AshutoshDash1999 as per GSSoC'24 guidelines please add label regarding level of issue and assign this PR to me.
> 
> Bro if you don't know whom to tag, just tag the project owner. I am only a contributor.

So sorry

**Comment by NitinChakrawarti** [comment]
@HimanshuNarware as per GSSoC'24 guidelines please add label regarding level of issue and assign this PR to me.

**Pull request merged**
