### PR TITLE
Add new feature : Social-Icon-hover-effect

### PR DESCRIPTION
**Pull request by Jagdeep30**
Modified the social icon css in footer.css file to make a hover effect on the social icons located at bottom of the page.

Modified the css for anchor tag in class

.cntc-link

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Jagdeep30  this PR is causing lot of errors can you share a video of your changes

**Comment by Jagdeep30** [comment]
Video of hover effect or the code changes?

Maybe the error might be because of the react-scripts package being updated

**Comment by Jagdeep30** [comment]
Here are the video and image of the changes in live as well as code: 


https://github.com/HimanshuNarware/Devlabs/assets/71442913/38eceb4e-86a6-4bfe-9b1f-6a4d682acf84

vs

**Comment by HimanshuNarware** [comment]
@Jagdeep30 it stead showing errors, make a 30 second video of you change, the main content of the website  is wiped out sometime

**Comment by Jagdeep30** [comment]
@HimanshuNarware 

https://github.com/HimanshuNarware/Devlabs/assets/71442913/ee7aaa42-d77c-4676-b887-09cba88c81bd

**Pull request closed without merging**
