### PR TITLE
Enhanced Mobile view of Footer Links

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Enhanced Mobile view of Footer Links by alligning them perfectly - Solved #1901 
Kindly Please go through this PR @panwar8279 

after

### CODE REVIEW

**Comment by panwar8279** [comment]
Please add 30 sec demo video

**Comment by sailaja-adapa** [comment]
https://github.com/user-attachments/assets/8d83e273-572f-4543-b86b-e40e767ebf59

Kindly go through this PR @panwar8279

**Comment by sailaja-adapa** [comment]
@panwar8279 kindly please add level label and assign me too

**Comment by sailaja-adapa** [comment]
@panwar8279 Please add level label and also assign me under GSSOC'24

**Comment by sailaja-adapa** [comment]
@panwar8279 kindly please add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
@panwar8279 please add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
@panwar8279 please add level label under GSSOC'24 since it is already merged

**Comment by sailaja-adapa** [comment]
@panwar8279 please add level label under GSSOC'24 for this Merged PR

**Comment by sailaja-adapa** [comment]
@panwar8279 please add level label under GSSOC'24 for this Merged PR

**Comment by sailaja-adapa** [comment]
@panwar8279 please add level label under GSSOC'24 for this Merged PR

**Comment by sailaja-adapa** [comment]
@panwar8279 Please add level label since it is already merged

**Pull request merged**
