### PR TITLE
#49 Center the Navbar items

### PR DESCRIPTION
**Pull request by sarthaksharma27**
Add CSS styling to center the Navbar items, creating a more visually appealing and centered layout.

### CODE REVIEW

**Comment by sarthaksharma27** [comment]
hey @HimanshuNarware finally the issue  is resolved please do check and provide me the feedback

**Comment by HimanshuNarware** [comment]
@sarthaksharma27  add issue number/code

**Comment by sarthaksharma27** [comment]
> @sarthaksharma27 add issue number/code

The issue name is "Add CSS Styling to Center Navbar Items" #49

**Comment by HimanshuNarware** [comment]
@sarthaksharma27  this is not looking good on navbar, try to use different size and position so that it looks good

**Pull request closed without merging**
