### PR TITLE
forage added

### PR DESCRIPTION
**Pull request by chaanakyaaM**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

#1124 

## Description
[Please include a brief description of the changes or features added]
 I have added the forage tool

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): Tool added

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
DEMO VIDEO:


https://github.com/HimanshuNarware/Devlabs/assets/131477601/26f38fd8-7e28-4c02-8e92-766886452a54

**Comment by chaanakyaaM** [comment]
@panwar8279 merge conflicts had been resolved.

**Comment by panwar8279** [comment]
@chaanakyaaM , There are some deployment error, please create new pr.

**Comment by chaanakyaaM** [comment]
ok

**Pull request closed without merging**
