### PR TITLE
added hover in social icon, it will scale and change opacity on hover

### PR DESCRIPTION
**Pull request by Surajit0573**
resolved Issues #14 
Screenshot 2023-10-01 160030
added hover in social icon, it will scale icon by 1.2 and change opacity to 1 on hover

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Surajit0573 Resolved conflicts

**Comment by Surajit0573** [comment]
@HimanshuNarware All conflicts resolved.

**Comment by HimanshuNarware** [comment]
> @Surajit0573 Resolved conflicts

@Surajit0573 Also add relative colors on the icons, like twitter have blue color

**Comment by Surajit0573** [comment]
@HimanshuNarware  Done, added relative colors on the icons on hover.

**Comment by Surajit0573** [comment]
@HimanshuNarware is there any problem !!

**Comment by HimanshuNarware** [comment]
@Surajit0573 This branch is causing lots of errors on the deployment, try recloning the entire codebase but this time first sync fork and update the branch, and then make changes and raise PR

**Pull request closed without merging**
