### PR TITLE
Trailing cursor

### PR DESCRIPTION
**Pull request by Chandu6702**
## Related Issue
closes : #732 

## Description
add the customized mouse movement for the cursor,A trailing effect adds for the cursor while moving through out the page

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/HimanshuNarware/Devlabs/assets/125206920/b77dbd01-d0f3-4ef6-9496-44383015cb53

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Chandu6702** [comment]
@HimanshuNarware and @panwar8279 I have updated the cursor as per your request . I hope it aligns with your requirements.

I have created a custom cursor, as we cannot directly make changes to the cursor, later I added a trailing effect to the custom cursor. And also updated CSS styles for optimal user experiences. I have re-written the code for it.


https://github.com/HimanshuNarware/Devlabs/assets/125206920/57c061ec-909c-42e5-9018-6684403741be


https://github.com/HimanshuNarware/Devlabs/assets/125206920/c12eaa6d-b699-4be7-914e-7b7a8b008174

Please review and merge this PR .

**Comment by GAVINESHWAR** [comment]
I am unable run the project after cloning it , i am getting the error like this:
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\Avineshwar G\AppData\Local\npm-cache\_logs\2024-06-18T03_33_38_120Z-debug-0.log

could you say steps how to run project after cloning the project @Chandu6702 
Thank you

**Comment by Chandu6702** [comment]
@panwar8279 can you please say what is the problem with this PR

**Comment by Chandu6702** [comment]
@panwar8279 @HimanshuNarware please review and merge this PR

**Pull request closed without merging**
