### PR TITLE
Improve the UI of the about section

### PR DESCRIPTION
**Pull request by ankittyagi140**
made necessary changes to Improve the UI of the about section

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@ankittyagi140  also removed the underline from the button

**Comment by ankittyagi140** [comment]
Hi @HimanshuNarware ,
like this? 
image

**Comment by HimanshuNarware** [comment]
@

> Hi @HimanshuNarware , like this? image

Yep

**Comment by ankittyagi140** [comment]
done, Please review and approve PR.

**Pull request merged**
