### PR TITLE
changed scrollbar background

### PR DESCRIPTION
**Pull request by amanr-dev**
Hi @HimanshuNarware, here is the fixed scrollbar Pull Request. Sorry that i forgot to push my code earlier, so here is the updated branch with the necessary changes.

Screenshot 2023-10-26 153941

### CODE REVIEW

**Comment by amanr-dev** [comment]
Hi @HimanshuNarware, could you please merge this pull request that changes the background of the scrollbar? Thanks! I'm sorry that I forgot to push my code earlier, so here is the updated branch with the necessary changes.

**Comment by HimanshuNarware** [comment]
@amanr-dev  also change the color of the scrollbar track and  also improve the scrollbar thumb  color it still not matching with the ui of the website

**Comment by amanr-dev** [comment]
@HimanshuNarware  have  a look

Dark mode:-
Screenshot 2023-10-26 222057

Light mode:-
Screenshot 2023-10-26 222110

and In the main scrollbar thumb, I can only set one background color because of the dark mode feature.

**Comment by HimanshuNarware** [comment]
@amanr-dev  looking good

**Comment by amanr-dev** [comment]
Hi @HimanshuNarware, the code has been pushed and is now ready to be merged👍

**Pull request merged**
