### PR TITLE
added tinkercad

### PR DESCRIPTION
**Pull request by ananyag309**
## Related Issue
#1817 

## Description
Added tinkercad

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [y ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by Kiran-pande-30 — CHANGES_REQUESTED** [review]
Hello @ananyag309, this tool is already present in the database.

**Comment by ananyag309** [comment]
@Kiran-pande-30 can i add Integromat tool removing that

**Comment by Kiran-pande-30** [comment]
@ananyag309 I am also a contributor like u, I was just saying don't add duplicate tools. 😅

**Comment by panwar8279** [comment]
> @Kiran-pande-30 can i add Integromat tool removing that

yes you can

**Pull request closed without merging**
