### PR TITLE
Corrected Router

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Corrected Routes - Solved #2457
Kindly go through this PR @panwar8279

https://github.com/user-attachments/assets/04764b8e-d3d6-4e33-beaf-092daa811a33

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@panwar8279 kindly please go through this PR

**Comment by sailaja-adapa** [comment]
@panwar8279 Kindly Please go through this PR

**Comment by sailaja-adapa** [comment]
Kindly go through this PR @panwar8279

**Comment by sailaja-adapa** [comment]
@panwar8279  please add GSSOC level label today is the last date upto 7 pm only

**Comment by panwar8279** [comment]
Please fix file conflict issue.

**Comment by sailaja-adapa** [comment]
@panwar8279 I solved the conflicts kindly go through this PR

**Pull request merged**
