### PR TITLE
fix pagination error

### PR DESCRIPTION
**Pull request by Rawshansharma**
fix issue #61 

pagination causing error

Screenshot 2023-10-18 012814
Screenshot 2023-10-18 012802

### CODE REVIEW

**Comment by Rawshansharma** [comment]
plzz check this pr @HimanshuNarware

**Comment by HimanshuNarware** [comment]
@Rawshansharma can you change the 40 box per page to 25 page per box

**Comment by Rawshansharma** [comment]
check this pr @HimanshuNarware

**Comment by Rawshansharma** [comment]
plzz check this pr @HimanshuNarware

**Comment by HimanshuNarware** [comment]
@Rawshansharma  i think this issue has been resolve by someone

**Pull request closed without merging**
