### PR TITLE
After Searching the user can go back by pressing Enter

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
#245 Revert Back to Home screen After Search Anything .

Use Case  :- When user search anything like scaler and then when user want to go back then Directly press enter after click on search bar

https://github.com/HimanshuNarware/Devlabs/assets/118350936/593d530d-b4fa-4408-9e6e-a0539a80e9f9

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Ayushmaanagarwal1211 mention issue number/code

**Comment by Ayushmaanagarwal1211** [comment]
done

**Comment by Ayushmaanagarwal1211** [comment]
Ya Sure .

**Comment by Ayushmaanagarwal1211** [comment]
Hii @HimanshuNarware  please add gssoc and level label to this pr

**Comment by Ayushmaanagarwal1211** [comment]
Hii @HimanshuNarware  please put gssoc and level label to be counted for leaderboard

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  Please add label and level 2 and assign me otherwise it will not be counted for leaderboard

**Pull request merged**
