### PR TITLE
Frontend folder and connection to backend

### LINKED ISSUE #150: Frontend to Backend Connection
**Is your feature request related to a problem? Please describe.**
Connect the frontend to backend by fetching data directly from the backend instead of product.json and open-source.json

**Describe the solution you'd like**
- Move frontend to a separate folder `frontend.
- Get the backend url from the environment file.
- make GET request to backend using axios to fetch the data before loading the page.
- display the fetched data on the webpage instead of displaying from .json files

> TO PERFORM THIS TASK, BACKEND URL IS REQUIRED FOR THE SENDING THE API-REQUEST FROM FRONTEND

Checklist
Example  Fill x { [x] }  into  bracket

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Slop 3.0 *

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by vihar-s1**
issue resolved #150 

### `Frontend` folder

Following files/folders are shifted to frontend folder (path with respect to root)
- public
- src
- .env
- .gitignore
- package.json
- package-lock.json

### Frontend to Backend Connection

- Modified code in `/frontend/src/components/Home.js` to fetch tools from backend.
- Modified code in `/frontend/src/components/OpenSource.js` to fetch tools from frontend.

-  Used `axios` to fetch data from backend using the API end point.

### Database Update

> Uploaded the JSON files of open-source projects and tools to the MongoDB database associated with the provided URI.

### Frontend

- Need to redeploy the frontend since the files are no longer in `root` folder.
- Set the Root Directory to "frontend".
    -  Example of setting "next-frontend" folder in the root directory as root directory for frontend
     image
- The frontend environment file will contain following environment variables
    - REACT_APP_BACKEND=<frontend-url> (eg. "http://127.0.0.1:8000")

### Backend

- Just like frontend, the backend deployment will also require to set the Root Directory as "backend".
- The backend environment file contains following environment variables
    - MONGODB_URI=<provided-mongodb-uri>
    - PORT=8000
    - FRONTEND_URL=<url-of-frontend-to-enable-cors> (use "*" to enable global access to backend else provide the frontend url)

### CODE REVIEW

**Comment by vihar-s1** [comment]
### `IMP INFO` - THE DEPLOYMENT MIGHT NOT WORK BECAUSE OF REFACTORING THE FRONTEND FOLDER SO PLEASE CHECK IT ACCORDINGLY.

**Comment by HimanshuNarware** [comment]
@vihar-s1  nice work, but can share a video of  you changes

**Comment by HimanshuNarware** [comment]
> Will do...I am not facing any problems currently but will definitely share if something occurs

ok,

**Comment by vihar-s1** [comment]
### Website Demo

https://github.com/HimanshuNarware/Devlabs/assets/96971096/50154d7b-b5eb-41e8-9f44-180cafb7c622

### Code Changes

https://github.com/HimanshuNarware/Devlabs/assets/96971096/1160223c-cd0b-4864-abdd-7bbde2e92b5e

### Modifications

Since the deployment fetches data from the backend, the database JSON files from the `src/db` folder are rendered unnecessary.

**Comment by vihar-s1** [comment]
@HimanshuNarware please respond to my PR...The deployment issue is because of refactoring the frontend code to frontend folder. If you don't want it like that I can undo those changes.

Please respond.

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware please respond to my PR...The deployment issue is because of refactoring the frontend code to frontend folder. If you don't want it like that I can undo those changes.
> 
> Please respond.

@vihar-s1  hm, ok is this issue resolve by refactoring the frontend code to frontend folder, if yes then you can  raise PR

**Pull request closed without merging**
