### PR TITLE
fix images on darkmode active

### PR DESCRIPTION
**Pull request by amanr-dev**
Fixed image when dark mode activated.

### before:
Screenshot 2024-03-19 133124
Screenshot 2024-03-19 133136
Screenshot 2024-03-19 133344

## after
Screenshot 2024-03-19 133200
Screenshot 2024-03-19 133152
Screenshot 2024-03-19 132949
Screenshot 2024-03-19 132931

### CODE REVIEW

**Comment by amanr-dev** [comment]
Hi @HimanshuNarware, review it.

**Comment by HimanshuNarware** [comment]
Bro you have mismatch the background of the theme, dark theme was in blue background

**Comment by amanr-dev** [comment]
> Bro you have mismatch the background of the theme, the dark theme was in blue background

Hi @HimanshuNarware, I have to change the dark theme color because of the images.

**Comment by amanr-dev** [comment]
> > Bro you have mismatch the background of the theme, the dark theme was in blue background
> 
> Hi @HimanshuNarware, I have to change the dark theme color because of the images.

I was trying to change the dark mode theme like as previous but  Images gets ruined

**Comment by HimanshuNarware** [comment]
but its not looking good, do one thing start working on the dark  mode from the strach

**Comment by amanr-dev** [comment]
Hi @HimanshuNarware , Review the PR.

**Comment by amanr-dev** [comment]
> but its not looking good, do one thing start working on the dark mode from the strach

As you said, I refactored the Darkmode feature.

**Comment by HimanshuNarware** [comment]
@amanr-dev  nice work, can you share a 30 sec video of you changes

**Comment by amanr-dev** [comment]
> @amanr-dev nice work, can you share a 30-sec video of your changes

https://github.com/HimanshuNarware/Devlabs/assets/124811276/86722783-1ae7-4df4-9dce-785b043251aa

**Comment by HimanshuNarware** [comment]
@amanr-dev  i think there is some error in code  deployment got failed everytime

**Comment by amanr-dev** [comment]
> @amanr-dev i think there is some error in code deployment got failed everytime

This is the error "GET https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1455524861/bhsyyazdiwk6qiwnertz.png 404 (Not Found)"

**Comment by amanr-dev** [comment]
> error

Some Images are not available.
Screenshot 2024-04-08 173307

**Comment by HimanshuNarware** [comment]
> > @amanr-dev i think there is some error in code deployment got failed everytime
> 
> This is the error "GET https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1455524861/bhsyyazdiwk6qiwnertz.png 404 (Not Found)"

can you share a video of this error,

**Comment by HimanshuNarware** [comment]
@amanr-dev  also do one thing i want to see is project is working properly in your machine or not , so that share a video of project

**Comment by amanr-dev** [comment]
> @amanr-dev also do one thing i want to see is project is working properly in your machine or not , so that share a video of project


https://github.com/HimanshuNarware/Devlabs/assets/124811276/3b0f5f98-8e94-4517-b7bb-584ca6074e6e

**Pull request closed without merging**
