### PR TITLE
UI Fixes (Footer + Responsive)

### PR DESCRIPTION
**Pull request by aayushwrld**
I have completed the UI Fixes as suggested in the Issue [215](https://github.com/HimanshuNarware/Devlabs/issues/215).

Also formatted the code for some files better readability.

### CODE REVIEW

**Comment by aayushwrld** [comment]
@HimanshuNarware Done with changes, please mark the PR under GSSoC'24.

**Comment by HimanshuNarware** [comment]
@aayushwrld share a demo video

**Comment by aayushwrld** [comment]
> @aayushwrld share a demo video


https://github.com/HimanshuNarware/Devlabs/assets/142794224/1c52b96f-1af6-479d-9d14-11c8c0e50358

**Comment by aayushwrld** [comment]
> @aayushwrld feel free to create more issues, and also starred our repo

Sure, please label it under GSSoC'24.

**Comment by aayushwrld** [comment]
@HimanshuNarware Please label under GSSoC'24 and put the required labels.

**Pull request merged**
