### PR TITLE
deployment and development server console errors cleared

### PR DESCRIPTION
**Pull request by vihar-s1**
# List of Changes Made

issue resolved: #98

## Changes in `src/index.js`

- ReactDOM imported from "react-dom" is outdated. Improved approach is to import it from "react-dom/client".

### _Change 1:_ /Navbar/NavbarItem.js

- Shifted Link tag out of the anchor tag, removed the anchor tag, and updated the Link tag className.

### _Change 2:_ Home.js

- Assigned a key datalist.productName to all the tools displayed on the page assuming components with unique names.
- Removed console.log statements displaying values of variables and unused variables.
- anchor tags in pagination component replaced with button due to use of href="#" is supported smoothly using buttons but not with anchor tag.

### _Change 3:_ Footer.js

- Removed additional unwanted attribute "px" present in the img tag of card-header. Provided alt="DevLaps" as alternate text.
- Renamed class attribute to className as used in REACT.

### _Change 4:_ /Sidebar/Sidebar.js

- Added link to about us page and open source projects page since they were inaccessible when viewed in a mobile screen. Modified `Navbar.css` as well to adjust the sidebar width for addition of a single link.
- Link tag brought out of anchor tag to remove the compile time warnings in the console occuring during running development server.

### _Change 5:_ About.js and Footer.js

total 9 `Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers` such errors solved.

### _Change 1:_ Navbar.css

- Improved CSS to adjust for the changes in Sidebar.js regarding all the navigation links and filters.
- Sidebar was not scrollable leading to content being cut-off at bottom so made it scrollable.

## Changes in `public/`

- These changes were more of code clean-up type changes rather than required changes. They still caused console errors which have now been resolved.

### _Change 1:_ Image Size Update

- logo192.png, and logo512.png did not match there corresponding sizes and aspect ratios as mentioned in manifest.json. So upscaled them and then downsized to get proper size with 1:1 aspect ratio.
- Also updated favicon.ico to follow the same.

### _Change 2:_ manifest.json

- Added additional size of 128x128 for favicon.ico.

### _Change 1:_ 4xx Errors

- Several logo links of the tools were either Gone (410), forbidden (403), or Not Found(404). Updated most of those Links.

### _Change 2:_ Insecure Links

- 15 Links were unsecure HTTP links. Converted them to HTTPS links.

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@vihar-s1 remove the open source and about us from the sidebar, only make changes on class to classname

**Comment by vihar-s1** [comment]
But then the about us page and open source project page won't be accessible to mobile devices

**Comment by HimanshuNarware** [comment]
> But then the about us page and open source project page won't have any access links for devices with width less than 580px

@vihar-s1  Then make it more attractive, you can go for  grid layout 2

**Comment by vihar-s1** [comment]
Will do

**Comment by vihar-s1** [comment]
@HimanshuNarware The sidebar was not reacting to "display:grid, grid-template-columns: repeat(2,1fr)" so resized the link fonts a bit and used flex-wrap to form the grid. Please check it once

**Comment by HimanshuNarware** [comment]
@vihar-s1 I Think you have done something wrong with light theme of the sidebar its  not changing

**Pull request closed without merging**
