### PR TITLE
Improve the Bookmark Page 

### PR DESCRIPTION
**Pull request by anand-harsh**
Improved Changes:

1) Footer stick to bottom of page.
2) If there is no Bookmark present, then display "No bookmarks found"

Solved Issue #182

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@anand-harsh  share a video of  before and after changes

**Comment by anand-harsh** [comment]
BEFORE:


https://github.com/HimanshuNarware/Devlabs/assets/94885893/9f3a80b4-1f08-4223-ab33-cfd80f76b629


AFTER:


https://github.com/HimanshuNarware/Devlabs/assets/94885893/96a6610d-4a1c-4497-bcca-617534d9011c

**Comment by HimanshuNarware** [comment]
@anand-harsh  feel free to create more issues, also starred our repo :)

**Comment by anand-harsh** [comment]
> @anand-harsh feel free to create more issues, also starred our repo :)

Sure, I have made a PR #186 and have more issues to create by the end of the day. Thanks for mentorship.

**Pull request merged**
