### PR TITLE
Added lightmode and darkmode feature

### PR DESCRIPTION
**Pull request by Mayank77maruti**
Addressing issue #90 , I've employed  Darkmode.js library to implement both light and dark user interfaces.

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  Nice, but the dark theme is not matching with our UI, 
Screenshot 2023-10-23 123611

give this kind of dark theme to web

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  also add this on navbar and footer

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  but the navbar is in same state ,also add same effect on the navbar

**Comment by Mayank77maruti** [comment]
Screenshot 2023-10-24 153606
Sir i have set the color of Navbar to what you mentioned in the image , do i need to change it any further. Can you please elaborate on your requirement for the navbar.

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  like when the user clicks on the theme changing button the background of the navbar and sidebar should change relative to the  theme of the website



chanage
chagne

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  the background of the navbar and sidebar is not changing relative to the theme of the website

**Comment by Mayank77maruti** [comment]
ok sir got it , adding the changes in some time.

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  I think you did something wrong with pagination , just see

**Comment by Mayank77maruti** [comment]
Sir I have checked the pagination and i think it is correct ,
If I require to make any changes to it please do convey me.

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  can you share 30 sec video of you changes

**Comment by Mayank77maruti** [comment]
https://github.com/HimanshuNarware/Devlabs/assets/125661248/e1884e8a-ab26-46e2-b923-b6a386ea8919

**Pull request merged**
