### PR TITLE
Signup/Login + Bookmarks (linking with user account)

### PR DESCRIPTION
**Pull request by rikhiltaneja**
#222 , Issue solved from my side! Please check and let me know if any changes required.

developed complete functionality of **signup and login** + developed **bookmarks** linking functionality with user account (backend)

### Things which I implemented (video proof):

https://github.com/HimanshuNarware/Devlabs/assets/142862928/a66897ce-925b-46a3-bb64-0e61ad06c96f

https://github.com/HimanshuNarware/Devlabs/assets/142862928/b82216bd-5498-4b8b-b03d-03c423da6cbe

Check the next comment as well! 😄 
(If you like my work, please assign me #241 to link all this functionality in the frontend side of website and make it actually user-ready)

### CODE REVIEW

**Comment by rikhiltaneja** [comment]
@HimanshuNarware Developed all the things mentioned in #222.

- [x] Signup + Login with JWT & Error Handling
- [x] Bookmark of Tools relationship with User Model (user account) 

You will have to add a JWT Password in Vercel Environment Variables. Keep the key name: JWT_PASS so that there is not conflict with the code.

Please merge this PR with the main branch. 😄

**Comment by HimanshuNarware** [comment]
@rikhiltaneja Nice work

**Comment by rikhiltaneja** [comment]
Thanks for the appreciation! 😄 @HimanshuNarware

**Comment by rikhiltaneja** [comment]
Please add the necessary GSSOC'24 labels to this PR. @HimanshuNarware

**Pull request merged**
