### PR TITLE
Fixes across Components to remove console errors

### PR DESCRIPTION
**Pull request by vihar-s1**
# List of Changes Made

**_ISSUE RESOLVED: #98_**

### _Change 1:_ /Navbar/NavbarItem.js

- Shifted Link tag out of the anchor tag, removed the anchor tag, and updated the Link tag className.

### _Change 2:_ Home.js

- Assigned a key datalist.productName to all the tools displayed on the page assuming components with unique names.
- Removed console.log statements displaying values of variables.

### _Change 3:_ Footer.js

- Additional unwanted attribute "px" was present in the img tag of card-header. Removed it.
- Renamed class attribute to className as used in REACT.

### _Change 4:_ /Sidebar/Sidebar.js

- Added link to about us page since the page was inaccessible when viewed in a mobile screen. Modified `Navbar.css` as well to adjust the sidebar width for addition of a single link.
- Link tag brought out of anchor tag to remove the compile time warnings in the console occuring during running development server.

## Changes in `public/`

- These changes were more of code clean-up type changes rather than required changes. They still caused console errors which have now been resolved.

### _Change 1:_ Image Size Update

- logo192.png, and logo512.png did not match there corresponding sizes and aspect ratios as mentioned in manifest.json. So upscaled them and then downsized to get proper size with 1:1 aspect ratio.
- Also updated favicon.ico to follow the same.

### _Change 2:_ manifest.json

- Added additional size of 48x48 for favicon.ico.

### _Change 1:_ 4xx Errors

- Several logo links of the tools were either Gone (410), forbidden (403), or Not Found(404). Updated some of those Links.

### _Change 2:_ Insecure Links

- 3 of the requests were over HTTP instead of HTTPS. Resolved all of those.

### CODE REVIEW

**Comment by vihar-s1** [comment]
Some of the link errors where not from product.json. I couldn't find where they were so those are the only ones who post error message of CANNOT GET <link>.
Please approve the PR

**Comment by vihar-s1** [comment]
@HimanshuNarware please merge this PR.

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware please merge this PR.

@vihar-s1  first resolve  issues

**Comment by vihar-s1** [comment]
This are new issues which recently popped up. Will fix them.

**Comment by HimanshuNarware** [comment]
> This are new issues which recently popped up. Will fix them.

@vihar-s1 there are some typo mistakes

**Comment by vihar-s1** [comment]
Where?

**Comment by HimanshuNarware** [comment]
Screenshot 2023-10-24 194631

**Comment by vihar-s1** [comment]
ok! will do

**Comment by vihar-s1** [comment]
I am closing this PR and opening a new one with the required changes.

**Pull request closed without merging**
