### PR TITLE
added Angular Snippet for types and html

### LINKED ISSUE #1690: [New Tool]: Angular Snippet for TypeScript and HTML.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Angular Snippet Extension  for TypeScript and HTML.

### Use Case

Type part of a snippet, press enter, and the snippet unfolds.

Alternatively, press Ctrl+Space (Windows, Linux) or Cmd+Space (macOS) to activate snippets from within the editor.

### Benefits

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Maheshwari-Love**
## Related Issue
closed #1690
## Description
added Angular Snippet for types and html
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by panwar8279** [comment]
Please fix file conflict issue.

**Comment by Maheshwari-Love** [comment]
> Please fix file conflict issue.

@panwar8279 fixed the conflicts

**Comment by Maheshwari-Love** [comment]
@panwar8279 kindly merge this pr

**Comment by Maheshwari-Love** [comment]
@panwar8279 it has been 2 weeks please merge this pr Already my 6-7 issues were closed , tomorrow is last day

**Comment by panwar8279** [comment]
There are some deployment errors. Please Create a new PR.

**Pull request closed without merging**
