### PR TITLE
Images Of The Cards Fixed

### PR DESCRIPTION
**Pull request by Mayank77maruti**
Images Of Some Cards were not showing those were fixed .

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  share screenshots

**Comment by Mayank77maruti** [comment]
BEFORE
scr3
scr2
scre1
issuegithub2
NOW
SCRE77
there were many cards those were not showing image i forgot to take all of the screenshots but have fixed them.

**Comment by Mayank77maruti** [comment]
Hi @HimanshuNarware, could you please merge this pull request that fixes the images of cards that donot appear properly? 
And Sir Please do Assign Me the next set of Issues I have opened since  I have completed the required changes and I am eager to contribute further to the project.

**Comment by Mayank77maruti** [comment]
Sir above I was trying to put a pull request for the issue i have raised #129 but i by mistakenly commited it here .Sir in the pagination negation fixed commit i have changed only the home.js file so please donot consider the changes made in home.js for this pull request .

**Comment by Mayank77maruti** [comment]
In the lastest commit i have corrected the mistake and for fixing the images of cards i made changes only to product.json file and added some files.

**Comment by HimanshuNarware** [comment]
@Mayank77maruti every time you raise PR kindly add issue number

**Pull request merged**
