### PR TITLE
Added contents on the UI page.

### PR DESCRIPTION
**Pull request by meetarora10**
## Related Issue
As per the issue #1114 I have added contents on the UI page.

## Description
I have added contents on the UI page and now it looks similar to other pages.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/HimanshuNarware/Devlabs/assets/143121854/5459578b-5540-4ac3-b370-25ead3df6eee

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by meetarora10** [comment]
@panwar8279 please review this PR.

**Comment by meetarora10** [comment]
Hi @panwar8279 can you please take a moment to review this PR.

**Comment by panwar8279** [comment]
@meetarora10 , There are some deployment error, please create new pr.

**Comment by meetarora10** [comment]
@panwar8279 I will create a new PR then.

**Comment by meetarora10** [comment]
@panwar8279 I have added a new PR related to this issue.
Kindly review it.

**Pull request closed without merging**
