### PR TITLE
Negation Of Pagination Fixed #129 issue number

### LINKED ISSUE #129: Pagination Number Shows Negative Number When Clicked Previous After Page Number 1
Video Describing The Bug:

https://github.com/HimanshuNarware/Devlabs/assets/125661248/7f7e4b95-45e6-4ce3-a1bf-1caa2c52314e

Example  Fill x { [x] }  into  bracket

- [1] I have checked the existing issues *
- [1] I have read the Contributing Guidelines *
- [1] I have starred the repository *
- [1] Working under Hacktomberfest/Hacksquad*
- [1] Working under Slop 3.0 *
- 
Sir , please assign this task to me .

### PR DESCRIPTION
**Pull request by Mayank77maruti**
#129 where pagination became negative is fixed

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  resolved conflicts

**Comment by Mayank77maruti** [comment]
Sir , I have resolved the conflicts , So sir please do review and merge it.

**Comment by Mayank77maruti** [comment]
Sir as hacktober fest is approaching its end , it would be a great help if you review and merge this PR at your earliest .

**Comment by Mayank77maruti** [comment]
Sir I have resolved the conflicts so sir please do review the code and merge it since hacktoberfest is close to end it would be a great help if you could merge it at your earliest.

**Pull request merged**
