### PR TITLE
Fixed sidebar scroll and added scrollbar

### LINKED ISSUE #122: Sidebar isn't scrolling down properly
**Describe the bug**
The sidebar is not scrolling to the downside properly.

**Expected behavior**
The sidebar should scroll properly.

**Hints**
Add overflow: "scroll" to the sidebar and also add a scrollbar.

### PR DESCRIPTION
**Pull request by amanr-dev**
Hi @HimanshuNarware , fixed #122

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@amanr-dev also fix the background color of the  main  scrollbar,

**Comment by amanr-dev** [comment]
> @amanr-dev also fix the background color of the main scrollbar,

Working on it.

**Comment by amanr-dev** [comment]
Hi @HimanshuNarware , review the PR

**Comment by amanr-dev** [comment]
It's difficult to make the main scrollbar's background the same because of the Dark mode feature.

**Comment by HimanshuNarware** [comment]
Screenshot 2023-10-26 110320

**Comment by amanr-dev** [comment]
It can be challenging to make the scrollbar background match in both light and dark modes.

**Comment by amanr-dev** [comment]
So what should I do?

**Comment by amanr-dev** [comment]
In the main scrollbar, I can only set one background color - either green or purple.

**Comment by amanr-dev** [comment]
So what you want to do

**Comment by amanr-dev** [comment]
Should I change the scrollbar background to this

Screenshot 2023-10-26 153941

**Pull request merged**
