### PR TITLE
Fix: Duplicate Components and thier respective css files

### LINKED ISSUE #1907: [Bug]: Multiple Files in Codebase
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have multiple files for the following components: 

1. Extension.jsx having 2 extension.css file
2. Movie.jsx and Movies.jsx 
3. UI.jsx and UserInterface.jsx
4. RemoteJob.jsx and Remotejobs.jsx
5. Movie.css and Movies.css
6. remotejob.css and remotejobs.css
7. UI.css and UserInterface.css

### Expected behavior

There should not be multiple files for better workflow and file management

### Add ScreenShots

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Kiran-pande-30**
## Related Issue
Fixes #1907 

## Description
I have removed the duplicate files in our Codebase. I have also checked it doesn't affect the performance of the application.

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/ea607868-a3fe-41e8-a5e8-582ff1ecfd0f

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X]  I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
I have there is no unnecessary or error causing code  in this Pull request.

### CODE REVIEW

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279, please review this PR, it can create merge conflicts.

**Comment by Kiran-pande-30** [comment]
Hello, @panwar8279 there are 2 .jsx files for both extensions and movie, can you please suggest from the main branch which file is to eliminate.

**Comment by Kiran-pande-30** [comment]
@panwar8279 please address this issue

**Comment by panwar8279** [comment]
Please resolve file conflict issue.

**Pull request closed without merging**
