### PR TITLE
searchbar functionality resolved

### PR DESCRIPTION
**Pull request by Vidhanvyrs**

### CODE REVIEW

**Comment by Vidhanvyrs** [comment]
hey @HimanshuNarware  finally the issue is resolved please do check and provide me the feedback

**Comment by HimanshuNarware** [comment]
@Vidhanvyrs  please add issue code

**Comment by Vidhanvyrs** [comment]
the issue name and code is following : Search bar is not working #1

**Comment by HimanshuNarware** [comment]
@Vidhanvyrs  feel free to create more issues, and starred our repository

**Comment by Vidhanvyrs** [comment]
hey @HimanshuNarware  I have resolved this issue under the label of hacktoberfest i don't understand why it is excluded from it if possible can you please put back it under the label of hacktoberfest as it is my first hacktober and i have really worked hard for it 🙇‍♂️

**Pull request merged**
