### PR TITLE
mailing endpoint and mailing feature

### LINKED ISSUE #163: Mailing Endpoint and review
**Is your feature request related to a problem? Please describe.**
The review Page send mail button does not actually send the mail. Just alerts user about it not working.

**Describe the solution you'd like**
When clicked send, a loading message appears to show inform user of request being processed, user will get alert indicating that the mail has been sent, otherwise error message will be shown.

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [ ] Working under Hacktomberfest/Hacksquad*
- [x] Working under Slop 3.0 *

### PR DESCRIPTION
**Pull request by vihar-s1**
issue resolved #163 

### config/nodemailer.js

Using nodemailer, created `transporter` instance. Also created a `mailOptions` dictionary defining "to" and "from" for the mail.

### controllers/specialController.js

Generates email body using simple html layout and using the predefined `transporter` instance to send the mail. Note that the user sending the mail does not get any mail. User is alerted when the mail is sent.

### routes/special.js

defining router for mailing endpoint.

### src/component/Review.js

Modified code to send post request to the endpoint.

## Deployment Modifcations

add following environment variables to the `backend` environment file

```bash
MAIL=<mail from which send to yourself>
PASSWORD=<passkey corresponding to above mail>
```

## Video Demo

https://github.com/HimanshuNarware/Devlabs/assets/96971096/529b2d36-4c51-40f4-b4f6-6e39b58ad574

### CODE REVIEW

**Comment by vihar-s1** [comment]
Do you want the review sender to also receive the mail? 
If so, I can add the mail provided in "TO" field while your mail (taken from environment file) will go in BCC preventing the reviewer to know the mail Id to which the review goes.

**Comment by vihar-s1** [comment]
Do you want the review sender to also receive the mail? 
If so, I can add the mail provided in "TO" field while your mail (taken from environment file) will go in BCC preventing the reviewer to know the mail Id to which the review goes.

From: env-mail
To: reviewer-mail
BCC: env-mail

**Comment by HimanshuNarware** [comment]
> ### QUERY
> Do you want the review sender to also receive the mail? If so, I can add the mail provided in "TO" field while your mail (taken from environment file) will go in BCC preventing the reviewer to know the mail Id to which the review goes.
> 
> ### Modified Email Headers Will Be
> From: env-mail To: reviewer-mail BCC: env-mail
> 
> ### Current Email Headers
> From: env-mail To: env-mail

ok go for it

**Comment by vihar-s1** [comment]
Updated the code to match the suggested changes

**Comment by HimanshuNarware** [comment]
@vihar-s1 share a of changes,

**Comment by HimanshuNarware** [comment]
@vihar-s1  share a video of your changes.

**Comment by vihar-s1** [comment]
Already shared a video of the changes in the Pull request message. The only added difference is that the review writer will also receive a mail.

**Comment by HimanshuNarware** [comment]
> Already shared a video of the changes in the Pull request message. The only added difference is that the review writer will also receive a mail.

when ever you raise pr make video of code and deployment, it save lots of time during review code

**Comment by vihar-s1** [comment]
> > Already shared a video of the changes in the Pull request message. The only added difference is that the review writer will also receive a mail.
> 
> when ever you raise pr make video of code and deployment, it save lots of time during review code

Ok

**Comment by HimanshuNarware** [comment]
give @vihar-s1 150 points

**Comment by vihar-s1** [comment]
@HimanshuNarware please re assign the points....they are not updated on leaderboard

**Comment by HimanshuNarware** [comment]
give @vihar-s1 150 points

**Comment by HimanshuNarware** [comment]
give @vihar-s1 150 points

**Comment by HimanshuNarware** [comment]
give @vihar-s1 150 points

**Comment by HimanshuNarware** [comment]
give @vihar-s1 150 points

**Pull request merged**
