### PR TITLE
Made Contact form working

### PR DESCRIPTION
**Pull request by zalabhavy**
## Related Issue
issue no #1443

## Description

Added error message and success message when user submit form without fill details it will show error message if form details are filed and then submit form so user will get success message.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://www.loom.com/share/06e934e6733b4598bd7bcbc43765131f

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@panwar8279 Please check it and merge !

Thank You !

**Comment by zalabhavy** [comment]
@panwar8279 Please check it and merge !

Thank You !

**Comment by panwar8279** [comment]
@zalabhavy , please add 30 sec demo video.

**Comment by zalabhavy** [comment]
@panwar8279 already added in issue this is link 

https://www.loom.com/share/06e934e6733b4598bd7bcbc43765131f

**Comment by zalabhavy** [comment]
@panwar8279 Please check my PR and merge !

Thank You !

**Comment by zalabhavy** [comment]
@panwar8279 Please check it and merge !

**Comment by zalabhavy** [comment]
@panwar8279 Please check and merge my PR !

Thank You !

**Comment by panwar8279** [comment]
@zalabhavy , Please add 30sec demo video.

**Comment by zalabhavy** [comment]
@panwar8279 

https://github.com/user-attachments/assets/1b0767b0-36b4-4e1b-9e28-f46300ba10bc

**Comment by zalabhavy** [comment]
@panwar8279 Done !
Please check it and merge !
Now I am understand how to make PR properly with add Videos. **Thank You !**

**Comment by zalabhavy** [comment]
@panwar8279 please check it and merge !

**Comment by zalabhavy** [comment]
@panwar8279 Please merge it so i can start my work on another issue and make PR for it !
https://github.com/user-attachments/assets/1b0767b0-36b4-4e1b-9e28-f46300ba10bc
Thank You !

**Comment by panwar8279** [comment]
@zalabhavy , You are doing good. 
But there are some deployment error so just create new pr for this.

**Pull request closed without merging**
