### PR TITLE
UI Fix + Responsive Fix

### PR DESCRIPTION
**Pull request by aayushwrld**
Issue - [215](https://github.com/HimanshuNarware/Devlabs/issues/215)

I have fixed the problems as mentioned in the issue.

image

image

### CODE REVIEW

**Comment by aayushwrld** [comment]
@HimanshuNarware Please check and merge!

**Comment by HimanshuNarware** [comment]
@aayushwrld  responsiveness is ok but do not make any changes in the navbar section, update you code ok then I accept your PR

**Comment by aayushwrld** [comment]
@HimanshuNarware Okay, so shall I remove the changes in the Navbar?

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware Okay, so shall I remove the changes in the Navbar?

Yep

**Comment by aayushwrld** [comment]
@HimanshuNarware Done, I removed the Navbar changes, please merge and put it under GSSoC'24.

**Comment by HimanshuNarware** [comment]
@aayushwrld  check your code deployment is failed

**Comment by HimanshuNarware** [comment]
@aayushwrld check your code.  the deployment has failed

**Comment by aayushwrld** [comment]
@HimanshuNarware I will create a new PR shortly.

**Pull request closed without merging**
