### PR TITLE
[FIX] The X logo fixed for issue #210

### PR DESCRIPTION
**Pull request by AmitBiswas1402**
So the X logo is now looking like this for #210 

image

### CODE REVIEW

**Comment by AmitBiswas1402** [comment]
Hey @HimanshuNarware review this PR

**Comment by HimanshuNarware** [comment]
@AmitBiswas1402  deployment is failled check your code





+

**Comment by AmitBiswas1402** [comment]
Hey @HimanshuNarware check it, now deployment is showing successful

**Comment by HimanshuNarware** [comment]
@AmitBiswas1402  but the hover effect of the icon not working now , fix this also

**Comment by AmitBiswas1402** [comment]
Hey @HimanshuNarware I am not able to do the hover effect as the logo is not from the react-icons package, but your original website's X logo also doesn't have a hover effect, so can you consider my contribution? Also, I tried to use the X logo from react-icons but showing "logo not found in react-icons/pi" so that's why I am saying

**Comment by HimanshuNarware** [comment]
> Hey @HimanshuNarware I am not able to do the hover effect as the logo is not from the react-icons package, but your original website's X logo also doesn't have a hover effect, so can you consider my contribution? Also, I tried to use the X logo from react-icons but showing "logo not found in react-icons/pi" so that's why I am saying

may be icon present in another lib of react-icon,

**Comment by AmitBiswas1402** [comment]
image
Hey @HimanshuNarware so the logo looks like this now, I've removed the X logo and replaced it with the Twitter bird logo as it was creating problems maybe it was from the "react-icons/pi" group not from react-icons/anything else (I guess that's been doing the issue). Anyway, I have made it I have added the Gmail logo instead of that email logo, it looks pretty nice and has a hover effect too. Have a look and review.

**Comment by HimanshuNarware** [comment]
@AmitBiswas1402  feel free to create more issues .  also starred our repo

**Comment by AmitBiswas1402** [comment]
Oh thanks for the merging 😊

**Pull request merged**
