### PR TITLE
updated the card design

### PR DESCRIPTION
**Pull request by Anjali-Kedia**
Updated the card UI design.
Screenshot 2023-10-18 at 6 35 16 PM
Please let me know if there are any changes to be made.
Thank you!

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Anjali-Kedia  nice ,but  is affecting the responsiveness of the website,

add this


Resolve this  too

**Comment by Anjali-Kedia** [comment]
@HimanshuNarware Could you let me know which dimension you  are checking on, it is working fine for all sizes on my end. I can update for that specific dimension. I have attached Screenshots for your reference.
Screenshot 2023-10-18 at 7 38 59 PM
Screenshot 2023-10-18 at 7 38 52 PM
Screenshot 2023-10-18 at 7 38 31 PM
Screenshot 2023-10-18 at 7 38 21 PM

**Comment by Anjali-Kedia** [comment]
@HimanshuNarware could you update me on the changes, thank you

**Comment by HimanshuNarware** [comment]
@Anjali-Kedia  from 665px to 775 px

**Comment by Anjali-Kedia** [comment]
@HimanshuNarware Corrected the responsiveness, do let me know for any other changes!

**Comment by HimanshuNarware** [comment]
@Anjali-Kedia add issue number/code

**Comment by Anjali-Kedia** [comment]
@HimanshuNarware The issue number is #83

**Comment by HimanshuNarware** [comment]
@Anjali-Kedia  feel free to create more issues, also starred our repo 👍

**Pull request merged**
