### PR TITLE
Feat/backend for website

### PR DESCRIPTION
**Pull request by vihar-s1**
# List of Changes Made

issue resolved: #139

## Environment Variables Required

> Default environment variables used for backend

- MONGODB_URI="mongodb://127.0.0.1:27017"
- PORT=8000
- FRONTEND_URL="*"

### Tool

| _Attribute Name_ | _Type_ | _Required_ | _Unique_ |
| ---------------- | ------ | ---------- | -------- |
| productName      | String | true       | false    |
| category         | String | true       | false    |
| image            | String | true       | false    |
| link             | String | true       | true     |
| description      | String | true       | false    |

> category is of type enum: ['remote', 'resume', 'tweet', 'ai', 'ethical', 'movies', 'extensions', 'tools']

### OpenSource

| _Attribute Name_ | _Type_   | _Required_ | _Unique_ |
| ---------------- | -------- | ---------- | -------- |
| projectName      | String   | true       | false    |
| ownerUsername    | String   | true       | false    |
| tags             | [String] | true       | false    |
| link             | String   | true       | true     |
| description      | String   | true       | false    |

## Controller Created

| _Controller Name_    | _Function Name_  | _Description_                        |
| -------------------- | ---------------- | ------------------------------------ |
| Tools                | addTool          | function to add a new tool           |
| Tools                | fetchAllTools    | fetch all tools from the database    |
| Open Source Projects | addProject       | function to add a new project        |
| Open Source Projects | fetchAllProjects | fetch all projects from the database |

## Routes Created

| _Controller Name_    | _EndPoint_              | _Description_                        |
| -------------------- | ----------------------- | ------------------------------------ |
| Tools                | (POST) /tools/add       | endpoint to add a new tool           |
| Tools                | (GET) /tools/all        | fetch all tools from the database    |
| Open Source Projects | (POST) /open-source/add | endpoint to add a new project        |
| Open Source Projects | (GET) /open-source/all  | fetch all projects from the database |

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@vihar-s1  Explain all changes

**Comment by vihar-s1** [comment]
Just created a backend with models, controllers for adding and fetching tools and open source projects, and created routes corresponding to those controllers no changes have been made to the frontend yet.

 To run the backend, you will have to provide MONGODB_URI, BACKEND PORT, and FRONTEND_URL as the environment variables.

Once you deploy backend, then I will update the database through /tools/add and open-source/add endpoints to contain the data and use axios to fetch the data in frontend. This way, the site will have a functioning backend without and won't have to go without any tools to display inbetween

**Comment by vihar-s1** [comment]
Also, I would have refactored the frontend code in `frontend` folder but that would have caused the deployment to fail since vercel would no longer find anything to deploy in the root folder

**Comment by HimanshuNarware** [comment]
@vihar-s1  share a video on instruction as well as  your plane to setup frontend with backend

**Comment by vihar-s1** [comment]
Following is the video explaining deployment and changes to be made in frontend to backend connection. Note that once backend is deployed, I will upload the database to the backend through a custom script before forming the connections to ensure that the website page is not empty.

ALSO, DUE TO SORE THROAT, I CANNOT SPEAK RIGHT NOW SO I AM TYPING WHATEVER I WANT TO COMMUNICATE IN THE FOLLOWING VIDEO

https://github.com/HimanshuNarware/Devlabs/assets/96971096/089c4f9a-b347-41e3-936b-87f13e0d5836

**Comment by vihar-s1** [comment]
@HimanshuNarware please merge my PR. I cannot move ahead with additional features like linking frontend and backend or the mailing endpoint untill you do not merge this PR and deploy the backend.

**Comment by HimanshuNarware** [comment]
give @vihar-s1 175 points

**Comment by HimanshuNarware** [comment]
@vihar-s1  for now use this mongoURl
mongodb+srv://harshitghanekar:<password>@cluster0.ukw8c0z.mongodb.net/?retryWrites=true&w=majority
and the password is Himanshu

**Comment by HimanshuNarware** [comment]
give @vihar-s1 150 points

**Pull request merged**
