### PR TITLE
Cleared Console errors of development and deployed server

### PR DESCRIPTION
**Pull request by vihar-s1**
# List of Changes Made

issue resolved: #98

### _Change 1:_ /Navbar/NavbarItem.js

- Shifted Link tag out of the anchor tag, removed the anchor tag, and updated the Link tag className.

### _Change 2:_ Home.js

- Assigned a key datalist.productName to all the tools displayed on the page assuming components with unique names.
- Removed console.log statements displaying values of variables and unused variables.
- anchor tags in pagination component replaced with button due to use of href="#" is supported smoothly using buttons but not with anchor tag.

### _Change 3:_ Footer.js

- Removed additional unwanted attribute "px" present in the img tag of card-header. Provided alt="DevLaps" as alternate text.
- Renamed class attribute to className as used in REACT.

### _Change 4:_ /Sidebar/Sidebar.js

- Added link to about us page and open source projects page since they were inaccessible when viewed in a mobile screen. Modified `Navbar.css` as well to adjust the sidebar width for addition of a single link.
- Link tag brought out of anchor tag to remove the compile time warnings in the console occuring during running development server.

### _Change 5:_ About.js and Footer.js

total 9 `Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers` such errors solved.

### _Change 1:_ Navbar.css

- Improved CSS to adjust for the changes in Sidebar.js regarding all the navigation links and filters.
- Sidebar was not scrollable leading to content being cut-off at bottom so made it scrollable.

## Changes in `public/`

- These changes were more of code clean-up type changes rather than required changes. They still caused console errors which have now been resolved.

### _Change 1:_ Image Size Update

- logo192.png, and logo512.png did not match there corresponding sizes and aspect ratios as mentioned in manifest.json. So upscaled them and then downsized to get proper size with 1:1 aspect ratio.
- Also updated favicon.ico to follow the same.

### _Change 2:_ manifest.json

- Added additional size of 128x128 for favicon.ico.

### _Change 1:_ 4xx Errors

- Several logo links of the tools were either Gone (410), forbidden (403), or Not Found(404). Updated some of those Links.

### _Change 2:_ Insecure Links

- 15 Links were unsecured HTTP links. Converted them to HTTPS links.

### CODE REVIEW

**Comment by vihar-s1** [comment]
@HimanshuNarware can you please check and tell me why the check is failing? The code was running fine on my PC on development server.

**Comment by HimanshuNarware** [comment]
@vihar-s1  Syntax error: Identifier 'currentPage' has already been declared. (48:9) (48:9)

**Comment by vihar-s1** [comment]
Will update it 👍👍

**Comment by vihar-s1** [comment]
I am closing this again to reopen it due to the sudden 20 commit jump

**Pull request closed without merging**
