### PR TITLE
remove bookmark redux

### LINKED ISSUE #2558: [Bug]: Remove Bookmark not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,

### Expected behavior

it should removed from bookmark page

### Add ScreenShots

image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@panwar8279 

close #2558

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@panwar8279 

please check this and merge it
also add level as per #2558

**Comment by dhruv8433** [comment]
@panwar8279 

Kindly please check this and merge it

**Comment by panwar8279** [comment]
Please fix file conflict issue.

**Comment by dhruv8433** [comment]
@panwar8279 

now you can merge it

**Pull request closed without merging**
