### PR TITLE
Fixed Overlapping

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## Related Issue
closes : #1203 

## Description
I have fixed the overlapping of the heading with the navbar in different components 
I have also fixed the indentation in different components

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-07-03 224847

## Checklist:
- [ 
Screenshot 2024-07-03 224831

https://github.com/HimanshuNarware/Devlabs/assets/118350936/050a3379-44eb-4105-b3c7-48e71946d7fb

I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
<!x- [X] - put a cross/X inside [] to check the box -->

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by panwar8279** [comment]
@Ayushmaanagarwal1211 , Please solve file conflict issue.

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  solved please review

**Comment by panwar8279** [comment]
@Ayushmaanagarwal1211 , Add 30sec demo video.

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  Done please check

**Comment by panwar8279** [comment]
@Ayushmaanagarwal1211 , Resolve Extension file conflict issue.

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  Solved

**Comment by panwar8279** [comment]
@Ayushmaanagarwal1211 , Please check movie.tsx file.

**Comment by Ayushmaanagarwal1211** [comment]
@panwar8279  Fixed please review it asap otherwise it will create conflicts again and again

**Pull request merged**
