### PR TITLE
bug: cards not showing fixed

### PR DESCRIPTION
**Pull request by Lymah123**
This PR made changes to DevLabs app cards not showing issue.
 - This is the submission to the issue #160

### CODE REVIEW

**Comment by Lymah123** [comment]
Hi @HimanshuNarware , I fixed the rest of the cards that are not showing in the devlabs-one.vercel.app

**Comment by Lymah123** [comment]
> Hi @HimanshuNarware , I fixed the rest of the cards that are not showing in the devlabs-one.vercel.app

@HimanshuNarware , I am seeing failed in deployment. Would you be fixing it on your end? I tried to fix it here the resolved conflicts is not giving me access.

**Comment by HimanshuNarware** [comment]
@Lymah123 share screenshots of you changes

**Comment by Lymah123** [comment]
screencapture-github-HimanshuNarware-Devlabs-pull-165-files-2023-11-12-16_20_56


Here is it, @HimanshuNarware .

**Comment by HimanshuNarware** [comment]
@Lymah123  first update your repo than make changes

**Pull request closed without merging**
