### PR TITLE
Fixed the Go Home button on Error Page

### PR DESCRIPTION
**Pull request by rahulpoonia29**
As mentioned in issue https://github.com/HimanshuNarware/Devlabs/issues/193

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@rahulpoonia29 share a demo video

**Comment by rahulpoonia29** [comment]
@HimanshuNarware 
Demo video

https://github.com/HimanshuNarware/Devlabs/assets/140232466/2fc098b4-f2ef-48d0-b0b2-1c07ea8ed9f1

**Comment by rahulpoonia29** [comment]
@HimanshuNarware 
Demo video 

https://github.com/HimanshuNarware/Devlabs/assets/140232466/84e33296-6518-4c8b-9532-3dbf9f6588e9

**Comment by HimanshuNarware** [comment]
@rahulpoonia29  feel free to create more issues, also starred our repo :)

**Pull request merged**
