### PR TITLE
New Tools: 28 Tools added

### LINKED ISSUE #2293: [New Tool]: Add neumorphism
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Generate Soft-UI neumorphism effects

### Use Case

Generate Soft-UI neumorphism effects

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Kiran-pande-30**
## Related Issue
Fixes #2293 , #2291 #2290 , #2286 , #2283 , #2282 #2281, #2280,
#2279, #2278, #2276, #2274 , #2271, #2261, #2257, #2236, #2232, #2231 , #2230 , #2219 , #2217 #2216 , #2211
#2210, #2206 , #2205 , #2180 

## Description
28 Tools Added.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [X] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Kiran-pande-30** [comment]
@panwar8279 please review my pull request

**Comment by DharshiBalasubramaniyam** [comment]
@Kiran-pande-30, How can you work on others issues, even though they are not assigned to them?

**Comment by panwar8279** [comment]
Why you are working on others raised issue. its not fair, @Kiran-pande-30. Its your last time when i merged your pr. If you do the same thing again, then I will never merge that type of PR.

**Comment by Maheshwari-Love** [comment]
@panwar8279 what of our time wasted😔, if we are creating 4 issues it means we have searched for particular technologies which are not present I  the repo and then gave time to search that particular to follow guidelines and now we got to know that the work done has wasted. It is really not fair.

**Comment by Kiran-pande-30** [comment]
Hello to everyone affected by this PR.

I apologise for my mistake 🙏. From now onwards I will make sure I don't touch other contributors issues without permission.

**Comment by Maheshwari-Love** [comment]
> Hello to everyone affected by this PR.
> 
> I apologise for my mistake 🙏. From now onwards I will make sure I don't touch other contributors issues without permission.

but what our time wasted ,my 5-6 issue are closed by you only.

**Comment by Maheshwari-Love** [comment]
> Why you are working on others raised issue. its not fair, @Kiran-pande-30. Its your last time when i merged your pr. If you do the same thing again, then I will never merge that type of PR.

@panwar8279  then you can just revert this pr, because it really time consuming task to find the tools to add in project if you can't assign single issues then just say us in the comment to do so but main idea is to what to add next in the project and he just know by seeing the issue and inserted the details to make pr

**Comment by Kiran-pande-30** [comment]
Hello @Maheshwari-Love, @panwar8279 I am okay if u revert this PR.

And I apologise once again 🙏.

**Comment by Kiran-pande-30** [comment]
@Maheshwari-Love it would help the maintainer if u guys collect and contribute multiple tools in a single issue. I have seen many issues raised consequently. If u add multiple tools in one issue. It will help the maintainer to assign less issues and also review your PR's.

**Comment by Maheshwari-Love** [comment]
> @Maheshwari-Love it would help the maintainer if u guys collect and contribute multiple tools in a single issue. I have seen many issues raised consequently. If u add multiple tools in one issue. It will help the maintainer to assign less issues and also review your PR's.

@Kiran-pande-30 yes but that is task of maintainer to tell us but they are assigning single issue to all but that doesn't meant you will do what you want....

**Comment by Kiran-pande-30** [comment]
@Maheshwari-Love  it is just a suggestion. I am out of this Conversation now,  @panwar8279 please revert this PR.

**Comment by Unnimaya6122004** [comment]
Issues #2286 #2283 #2282 #2281 #2280 #2279 #2278 #2276 #2274 #2271 #2236 are my issues....I have worked hard for it ...can u pls assign me those issues sir

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279, as also agreed from @Maheshwari-Love, i should the label on this PR. I request you to please consider my efforts and label this PR accordingly

**Pull request merged**
