### PR TITLE
Alligned Navbar

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Alligned Navbar Perfectly - Solved #1656
Kindly Please go through this PR @panwar8279

op

### CODE REVIEW

**Comment by panwar8279** [comment]
Please add 30 sec demo video; why are you not working with updated code. There is no search bar in the navbar. But your code still has a search bar.

**Comment by sailaja-adapa** [comment]
OKk @panwar8279 i will remove the searchbar and work with updated code sorry for inconvience

**Comment by sailaja-adapa** [comment]
https://github.com/user-attachments/assets/7ea24560-d056-4955-bddb-883ca0c1b1a2

Kindly go through this PR @panwar8279

**Comment by panwar8279** [comment]
Try to fix navbar in single row.

**Comment by sailaja-adapa** [comment]
Okay @panwar8279

**Comment by sailaja-adapa** [comment]
https://github.com/user-attachments/assets/aef7238f-9afb-4053-8061-c0699ba3d820


is it okay now @panwar8279

**Comment by panwar8279** [comment]
can you see current navbar and work with that.

**Comment by sailaja-adapa** [comment]
Ok @panwar8279 I will work with that

**Pull request closed without merging**
