### PR TITLE
Solved 🐞"Chatbot" and "Scroll-to-Top button" Overlapping

### LINKED ISSUE #635: 🐞BUG: "Chatbot" and "Scroll-to-Top button" is Overlapping
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @HimanshuNarware and @panwar8279 
The chatbot button and scroll to top buttons are overlapping 

### Expected behavior

The "Scroll to Top" button and the WebChat bot should not overlap. Both elements should be easily accessible without interfering with each other.

### Add ScreenShots

image

### After clicking chatbot:

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
Issue closes #635 

## Description

Hey @HimanshuNarware and @panwar8279 I have resolved the overlapping issue of scroll to top button and chatbot button

## Type of PR

- [X] Bug fix

## Screenshots / videos (if applicable)

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@MastanSayyad  share a 30 sec video

**Comment by panwar8279** [comment]
There are some deployment error, Please create new PR.

**Comment by MastanSayyad** [comment]
@HimanshuNarware @panwar8279 


https://github.com/HimanshuNarware/Devlabs/assets/101971980/341d88b4-f843-401d-bb13-61cf0fc5cc5c

**Comment by MastanSayyad** [comment]
Dont worry, @panwar8279 it will work without any issue even after deployment error, it needs authorization for deployment. these are just minor CSS properties changes.

**Pull request closed without merging**
