### PR TITLE
Modified Default Scroll Bar

### PR DESCRIPTION
**Pull request by Vishal-1004**
## Modified Default Scroll Bar
Generally we have white and grey colored scroll bar provided by the bowser but it doesn't matches with our default color of the website and same problem was with your's website too. So I wrote a code to modify the scroll bar and now it looks as follows:
Screenshot (1384)

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Vishal-1004  Also add styling on the scrollbar track

**Comment by Vishal-1004** [comment]
@HimanshuNarware sure I can add color to it too,
But can you clearly tell me what color do you want me to give it which you also match your website color theme.

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware sure I can add color to it too, But can you clearly tell me what color do you want me to give it which you also match your website color theme.

@Vishal-1004 use dark shade color which match with the UI of the website

**Comment by Vishal-1004** [comment]
Does this looks good now @HimanshuNarware 
Screenshot (1391)

**Comment by HimanshuNarware** [comment]
> Does this looks good now @HimanshuNarware Screenshot (1391)

@Vishal-1004 decreases the opacity of the color, it should match with UI of  the website

**Pull request merged**
