### PR TITLE
Restructured and Modularized the Navbar into several components

### PR DESCRIPTION
**Pull request by hrid-chakraborty**
The Navbar has been further split into multiple components. This will help contributors to work on and test specific parts quite easily.

The components are:
1. Navbar Center
2. Navbar Left
3. Navbar Right

Also, the sidebar has been made into 2 components:
1. The main sidebar.
2. Sidebar Content (for various categories)

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@hrid-chakraborty  assigned you

**Comment by hrid-chakraborty** [comment]
Thank you

**Comment by HimanshuNarware** [comment]
give @hrid-chakraborty 150 points

**Comment by HimanshuNarware** [comment]
@hrid-chakraborty  nice, feel free to create more issue also starred our repo

**Comment by hrid-chakraborty** [comment]
Thank you

**Pull request merged**
