### PR TITLE
added the animated cursor and tilt effect to all cards  in home, bookmark & Open Source sections.

### PR DESCRIPTION
**Pull request by happyrao78**
## Related Issue
[NONE]

## Description
[I have added the animated cursor to the website for  more user interaction. Additionally I have also added tilt effect to all cards present in home section, bookmark section and the open source section also. ]

## Type of PR
-  Feature enhancement

## Screenshots / videos (if applicable)
solved issue #500 
Screenshot 2024-05-30 110229
Screenshot 2024-05-30 110245
Screenshot 2024-05-30 110256
Screenshot 2024-05-30 110313
Screenshot 2024-05-30 110327

## Checklist:
- [yes ] I have performed a self-review of my code
- [yes ] I have read and followed the Contribution Guidelines.
- [ yes] I have tested the changes thoroughly before submitting this pull request.
- yes[ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [yes ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by yeolesanskruti** [comment]
@happyrao78, please tell me how you completed the Deployment of the devlabs on Vercel. 
I am new to Vercel hence I am facing a problem with this.
Thank you.

**Comment by happyrao78** [comment]
@HimanshuNarware Kindly review the pr and merge it.

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware Kindly review the pr and merge it.

@happyrao78  share a 30 sec video

**Comment by happyrao78** [comment]
@HimanshuNarware there are multiple merge conflicts coming from other contributors.

**Comment by panwar8279** [comment]
There is some deployment error.

**Pull request closed without merging**
