### PR TITLE
Implemented Backend using Express and MongoDB

### PR DESCRIPTION
**Pull request by hrid-chakraborty**
Changes:
1. Created several API routes using express to enable CRUD operations on the MongoDB database.
2. In Home.js, used axios to fetch data from the database.
3. In Home.js, replaced the pagination block of code with a component from react-paginate. This fixes the error of going out of bounds when clicking next and previous button.
4. Fixed the issue where typing something on the search bar gave an error.

Instructions to use:
1. Run npm install on both the root directory as well as Devlabs-backend directory.
2. Add a .env file in the root directory and fill in the contents like so:
REACT_APP_BACKEND_URL={insert url here without curly braces}
3. Add a .env file in the Devlabs-backend directory and fill in the contents like so:
PORT_NUM={any port}
MONGODB_URL={either the mongodb atlas url or the local one}

Here is the demo (will be removed later):
Frontend: https://testdevlabsfrontend.netlify.app/
Backend: https://devlabs-backend.onrender.com

### CODE REVIEW

**Comment by hrid-chakraborty** [comment]
Just a quick note for the backend:
image

So if the cards don't render sometimes, it might be due to this.

**Comment by HimanshuNarware** [comment]
@hrid-chakraborty  share 1 min video of you changes.

**Comment by hrid-chakraborty** [comment]
Here is the drive link:
https://drive.google.com/file/d/1JK0g0HkUW5QjhRQgURLTVD0S-HRRZvLw/view?usp=share_link

**Comment by HimanshuNarware** [comment]
@hrid-chakraborty  the deployment of you PR showing me black page of devlabs

**Comment by hrid-chakraborty** [comment]
Have you input the environment variables?

**Comment by hrid-chakraborty** [comment]
Because it is saying this:
image

This could be possible when the value is itself undefined, which might happen due to not successfully fetching from the backend. 

Please check if you have set the environment variables in vercel.

**Comment by HimanshuNarware** [comment]
> Because it is saying this: image
> 
> This could be possible when the value is itself undefined, which might happen due to not successfully fetching from the backend.
> 
> Please check if you have set the environment variables in vercel.

Ok

**Comment by HimanshuNarware** [comment]
> Changes:
> 
> 1. Created several API routes using express to enable CRUD operations on the MongoDB database.
> 2. In Home.js, used axios to fetch data from the database.
> 3. In Home.js, replaced the pagination block of code with a component from react-paginate. This fixes the error of going out of bounds when clicking next and previous button.
> 4. Fixed the issue where typing something on the search bar gave an error.
> 
> Instructions to use:
> 
> 1. Run npm install on both the root directory as well as Devlabs-backend directory.
> 2. Add a .env file in the root directory and fill in the contents like so:
>    REACT_APP_BACKEND_URL={insert url here without curly braces}
> 3. Add a .env file in the Devlabs-backend directory and fill in the contents like so:
>    PORT_NUM={any port}
>    MONGODB_URL={either the mongodb atlas url or the local one}
> 
> Here is the demo (will be removed later): Frontend: https://testdevlabsfrontend.netlify.app/ Backend: https://devlabs-backend.onrender.com

@hrid-chakraborty  it is all clear from my side, Let's do one thing from your side, share a  video of instructions for setup, one thing:  have you added a feature for adding new tools

**Comment by hrid-chakraborty** [comment]
Front end url from new video: https://devlabs-theta.vercel.app/
Backend url from new video: https://testbackendxyz.onrender.com/

**Comment by hrid-chakraborty** [comment]
It will take some time to upload the video

**Comment by hrid-chakraborty** [comment]
Here is the link of the video detailing how I deployed the backend and the frontend:
https://drive.google.com/file/d/1Epey_GCMP8anx1PDFM4VU8hOIA_kPGlF/view?usp=share_link

**Comment by HimanshuNarware** [comment]
@hrid-chakraborty  its  still not working,

**Comment by HimanshuNarware** [comment]
I am closing this issue.

**Comment by hrid-chakraborty** [comment]
@HimanshuNarware please reopen the issue. We can discuss this on a call whenever you are free. This PR can allow many more contributors to contribute to the project. Please give it a chance.

**Comment by HimanshuNarware** [comment]
@hrid-chakraborty  ok

**Comment by hrid-chakraborty** [comment]
Thank you

**Comment by hrid-chakraborty** [comment]
@HimanshuNarware I have been unable to contact you on Element for some time now, and there have been many new commits such that the project might break if we do anything now. Please close this issue.

**Pull request closed without merging**
