### PR TITLE
Modify scroll bar

### PR DESCRIPTION
**Pull request by root-0101**
## Related Issue
#486 
## Description
Modify the scroll-bar with the existing theme and suitable for dark and light mode

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-05-24 230426

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by root-0101** [comment]
Please assign me the required levels for this PR

**Comment by root-0101** [comment]
Please assign me the required levels for this successfully merged PR

**Comment by root-0101** [comment]
Hey @HimanshuNarware @panwar8279 Please assign me the required levels for this successfully merged PR

**Comment by sanjay-kv** [comment]
@HimanshuNarware Please assign the levels to it, also add me into the repo so I can take care of these issues. Need your action asap. there are more people having same issue, eventually the contribution will be less if you ignore the contributor on your repos.

**Pull request merged**
