### PR TITLE
Addded new too to convert font online

### PR DESCRIPTION
**Pull request by Utsavladia**
## Related Issue #1619 
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
Tool to convert fonts online
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/7350b243-8345-4081-96b1-9ac38da815fd

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Utsavladia** [comment]
@panwar8279 Kindly review this PR gssoc is getting ended 😊

**Comment by Utsavladia** [comment]
@panwar8279 
Kindly merge this PR before closing of GSSOC 🙂

**Comment by panwar8279** [comment]
Please fix file conflict issue.

**Comment by Utsavladia** [comment]
@panwar8279 
Resolved ✅

**Pull request closed without merging**
