### PR TITLE
validation added

### PR DESCRIPTION
**Pull request by DevGajjar28**
## Related Issue
#2565

## Description
https://drive.google.com/file/d/1HRLEGG4fJGtv-8sWJHc2zsaihLFWtzJw/view?usp=sharing

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Kiran-pande-30** [comment]
Can u please explain what changes have you in Home,js??

**Comment by DevGajjar28** [comment]
> Can u please explain what changes have you in Home,js??

I have gotten error while updated the branch , started run locally and error showing that one div is not closed so I have only closed the open </div>

**Comment by Kiran-pande-30** [comment]
Is this PR the reason why the homepage is so much misaligned?

**Comment by DevGajjar28** [comment]
> Is this PR the reason why the homepage is so much misaligned?

Noo

**Comment by DevGajjar28** [comment]
I have just closed the open div that giving me an error while updated my branch

**Pull request merged**
