### PR TITLE
Burger menu links

### LINKED ISSUE #599: [BUG]: All Navigation Link redirect to home page
**Describe the bug**

@HimanshuNarware 
@panwar8279 

check this out

all this link redirect us to `/` route 
we can create seperate route for that

**Expected behavior**

currently they all redirect to home page

**Screenshots**

image

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@panwar8279 
[BUG]: All Navigation Link redirect to home page #599

close #599

## Description
[Please include a brief description of the changes or features added]

- i created all pages for burger menu links
- resolve all errors and conflicts from app.js

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
please check this and merge it

**Comment by dhruv8433** [comment]
@panwar8279 

i would like to work with you
can you please assign me whole page design of all this `footer` and `burger menu` links....

i will beautifully design those pages

**Comment by yeolesanskruti** [comment]
@dhruv8433 , please tell me how you completed the Deployment of the devlabs on Vercel.
I am new to Vercel hence I am facing a problem with this.
Thank you.

**Comment by dhruv8433** [comment]
@yeolesanskruti 

can you please tell me what kind of problem you faced in development..?
you just have to create one another branch and create pr, when project mentors or owners approve this pr it autometically deployed

**Comment by yeolesanskruti** [comment]
When I deploy the repository of my fork-
Screenshot 2024-06-02 173044

I am getting a 404 error.

Also,
after creating PR - I got to know I was facing deployment issues
So I tried the above deploying many times so I am confused as I am new to Vercel.
Screenshot 2024-06-02 172837
Screenshot 2024-06-02 172849

Thank you @dhruv8433 .

**Comment by HimanshuNarware** [comment]
@dhruv8433  share a 30 sec video

**Comment by dhruv8433** [comment]
@HimanshuNarware 

https://github.com/HimanshuNarware/Devlabs/assets/114583978/f80c678a-c37d-4a91-85b9-340af8849975

**Comment by dhruv8433** [comment]
@HimanshuNarware 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@HimanshuNarware 
@panwar8279 

please check this and merge it 
so i can make another pr

**Comment by dhruv8433** [comment]
@HimanshuNarware 
@panwar8279 

i completed another issue please merge this so i can make another pr

**Comment by dhruv8433** [comment]
@HimanshuNarware 

please merge it

**Comment by HimanshuNarware** [comment]
@dhruv8433  once review your code deployment got failed

**Comment by dhruv8433** [comment]
@HimanshuNarware 

now i resolve all conflicts and it is able to deploy
kindly please check it and merge it

**Comment by dhruv8433** [comment]
@HimanshuNarware 

please check this and merge it
i resolve all conflicts and errors 
now it is ready to deploy

**Pull request merged**
