### PR TITLE
Review page created

### PR DESCRIPTION
**Pull request by vihar-s1**
# List of Changes Made

issue resolved: #143

## New Page

A page for users to send their thoughts to the website owner.

image

Added Link to the review page in the footer

image

### CODE REVIEW

**Comment by vihar-s1** [comment]
I facing an issue here. Even though I have added the route to review page properly like other routes as shown here,
image

The navbar does not show up for review page and I cannot figure out why. Please help.
image

You can see the same in the preview as well.

**Comment by HimanshuNarware** [comment]
@vihar-s1 Improve the UI of the Review section

**Comment by vihar-s1** [comment]
Please suggest the changes as I am not great at designing UI.

**Comment by HimanshuNarware** [comment]
@vihar-s1  
r

**Comment by vihar-s1** [comment]
I have updated the form design and also figured out the navbar issue. It was because the navbar had position: fix which caused the issue. Problem resolved after using margin-top:8rem on the top-most component.

**Comment by HimanshuNarware** [comment]
@vihar-s1  where? I received reviews

**Comment by vihar-s1** [comment]
The email functionality is still remaining...i either need a backend to create a mailing endpoint or I need to use an external API which will require API keys and additional environment variables.

Please tell me your preferred approach.

**Comment by HimanshuNarware** [comment]
give @vihar-s1 75 points

**Comment by HimanshuNarware** [comment]
give @vihar-s1 75 points

**Pull request merged**
