### PR TITLE
fix(home): pagination and data layout

### PR DESCRIPTION
**Pull request by OgaDavid**
# I have made the layout responsive across various screen sizes.

https://github.com/HimanshuNarware/Devlabs/assets/104001201/d0d4aa2d-a256-4b5f-981e-ccda5eb5fa00

<br />
<br />

# I also fixed the pagination overflowing on smaller screens by adding a scrollbar for small devices.

https://github.com/HimanshuNarware/Devlabs/assets/104001201/bed8fa0a-ea88-4cb0-86c0-1521893e4248

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@OgaDavid The website Logo on the navbar is overlapping, also the navbar content needs a margin ,fix these issues

**Comment by OgaDavid** [comment]
ok

**Comment by OgaDavid** [comment]
ohh, it worked haha 😂😂

**Comment by OgaDavid** [comment]
I'm not the one making these changes

**Comment by HimanshuNarware** [comment]
@OgaDavid  share a 60-second video of you changes and the layout of web

**Comment by HimanshuNarware** [comment]
@OgaDavid  Nope, make entire layout responsive, not only the prev button

**Comment by OgaDavid** [comment]
Alright

**Comment by OgaDavid** [comment]
Bugs fixed:
- [x] Prev button overflowing on screen
- [x] Responsive layout

https://github.com/HimanshuNarware/Devlabs/assets/104001201/409516d1-da7f-4d3f-bfe3-20390d1ccb3c

**Comment by HimanshuNarware** [comment]
@OgaDavid  nice

**Comment by HimanshuNarware** [comment]
@OgaDavid  feel free to create more issues, also starred our repository

**Comment by OgaDavid** [comment]
Thank you @HimanshuNarware I'll definitely leave a star.

**Pull request merged**
