### PR TITLE
added the profile page

### PR DESCRIPTION
**Pull request by ayush-848**
## Related Issue
#1598

## Description
Added a profile icons

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by panwar8279** [comment]
Please Resolve the file conflict issue. 
Is there any profile page exist?

**Comment by ayush-848** [comment]
> Please Resolve the file conflict issue. Is there any profile page exist?

I have added the profile page

**Comment by ayush-848** [comment]
image
image
image
image
@panwar8279

**Comment by ayush-848** [comment]
@panwar8279 Please upgrade it to **LEVEL 3**

**Comment by panwar8279** [comment]
@ayush-848 , What's the need to add profile page?

**Comment by ayush-848** [comment]
> @ayush-848 , What's the need to add profile page?

I just wanted to add the icon.
Then I thought you told me to make a profile page

**Comment by ayush-848** [comment]
> Please Resolve the file conflict issue. Is there any profile page exist?

Here

**Comment by ayush-848** [comment]
@panwar8279 should i close this PR ??

**Pull request closed without merging**
