### PR TITLE
added `ai` page

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@panwar8279 

[Feature Request]: Create AI Page #618

## Description
[Please include a brief description of the changes or features added]

- added `ai page`

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

- laptop screen

image

- tablet screen

image

- phone screen

image

theme

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@panwar8279 

please check this and merge it
also add level label

**Comment by dhruv8433** [comment]
@panwar8279 

Please check this and merge it

**Comment by dhruv8433** [comment]
@panwar8279 

Please check this and merge it

**Comment by dhruv8433** [comment]
@panwar8279 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@panwar8279 

please check this and merge it

**Comment by panwar8279** [comment]
@dhruv8433 , Please check ai page is already exist.

**Comment by dhruv8433** [comment]
@panwar8279 

when i created issue, ai page missing so...

**Pull request closed without merging**
