### PR TITLE
An AI copywriting tool

### PR DESCRIPTION
**Pull request by Chandu6702**
## Related Issue
closes: #627 

## Description
added a new tool called copy.ai in the AI category## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [X] Other (specify): new tool

## Screenshots / videos (if applicable)
Screenshot 2024-06-02 113557

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Chandu6702** [comment]
@panwar8279  please review and merge this PR

**Comment by Chandu6702** [comment]
@panwar8279 please review and merge this PR

**Comment by HimanshuNarware** [comment]
@Chandu6702  share a 30 sec video

**Comment by Chandu6702** [comment]
@panwar8279 this is the sample video of using copy.io
It contains many prompts related to business,blogs etc
https://github.com/HimanshuNarware/Devlabs/assets/125206920/986db2fa-ceab-474d-b693-ead779a253f0

**Comment by Chandu6702** [comment]
@panwar8279 please review and merge this PR

**Comment by Chandu6702** [comment]
@panwar8279 please review and merge this PR

**Pull request merged**
