### PR TITLE
Added contribute here

### PR DESCRIPTION
**Pull request by ayush-848**
## Related Issue
#628 

## Description
Added "Contribute Here" in the footer

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ayush-848** [comment]
@panwar8279 now check

**Comment by ayush-848** [comment]
@panwar8279 please check the PR, the conflict are gone.

**Comment by panwar8279** [comment]
@ayush-848  Add 30sec demo video.

**Comment by ayush-848** [comment]
https://github.com/HimanshuNarware/Devlabs/assets/126975547/c48c2473-b380-4dc9-98b9-efa2535f2f61

**Comment by ayush-848** [comment]
> contribute.mp4

@panwar8279

**Comment by ayush-848** [comment]
@panwar8279 check it now

**Comment by ayush-848** [comment]
@panwar8279 please check it, the issues have been resolved

**Comment by ayush-848** [comment]
@panwar8279 Please merge it, its been days since I made this PR

**Pull request closed without merging**
